size_x: 100
size_y: 50
n_steps: 100
output_path:
boundary_conditions: 'mirror'
build_probability: 0.5
T_star: 5
minimum_area: 100
random_seed: 42
input_filepath: ''
initialization_mode: 'list'
neighboring_centrality_probability: 1.e-2
isolated_centrality_probability: 1.e-2